baseurl: '/'
languageCode: 'en-us'
title: 'wccalvin'
theme: 'hugo-tania'
paginate: 6

params:
  titleEmoji: ''
  socialOptions:
    github: 'https://github.com/wccalvin'

menu:
  header:
    - name: Articles
      url: '/articles/'
    - name: About
      url: '/about/'
  footer:
    - name: RSS
      url: '/index.xml'

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true
