baseURL = "/"
languageCode = "en-us"
title = "wccalvin"
theme = "archie"
copyright = "© wccalvin"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="light"
	useCDN=false

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/wccalvin"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3
